export enum Entities {
	TAG = 'Tag',
	BLOG = 'Blog',
	BLOG_TAG = 'BlogTag',
	FREQUENT_QUESTION_TYPE = 'FrequentQuestionType',
	FREQUENT_QUESTION = 'FrequentQuestion',
	GENDER = 'Gender',
	ENTITY = 'Entity',
	ROLE = 'Role',
	PERMISSION = 'Permission',
	USER = 'User',
	USER_LOG = 'UserLog',
	OTP_KEY_TYPE = 'OtpKeyType',
	OTP_KEY = 'OtpKey',
	CATEGORY = 'Category',
	VEHICLE = 'Vehicle',
	SCHEDULED_SERVICE_TYPE = 'ScheduledServiceType',
	SCHEDULED_SERVICE_STATUS = 'ScheduledServiceStatus',
	SCHEDULED_SERVICE = 'ScheduledService',
	SCHEDULED_SERVICE_RATING = 'ScheduledServiceRating',
	TESTIMONIAL = 'Testimonial',
}